version: 1.0.{build}

image: Visual Studio 2017 RC

shallow_clone: true
configuration: Release
platform: x64

build:
  parallel: true
  project: build/windows/slang.sln

test_script:
  - cmd: bin\x64\Release\unit_tests.exe