version: 1.0.{build}

image: Visual Studio 2017

shallow_clone: true
configuration: Release
platform: x64

install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  verbosity: minimal
  project: build/slang.sln

test_script:
  - cmd: tests\unittests\Release\unittests.exe