version: 1.0.{build}

image: Visual Studio 2017

shallow_clone: true
configuration: Release
platform: x64

install:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  verbosity: minimal
  project: build/slang.sln

test_script:
  - cmd: build\tests\unittests\Release\unittests.exe