version: 1.0.{build}

image: Visual Studio 2017

shallow_clone: true
configuration: Release
platform: x64

install:
  - cmd: tools\bin\windows\genie.exe vs2017

build:
  parallel: true
  verbosity: minimal
  project: build/projects/vs2017/slang.sln

test_script:
  - cmd: build\win64_vs2017\bin\unittestsRelease.exe