version: 1.0.{build}

image: Visual Studio 2017

shallow_clone: true
configuration: Release
platform: x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 15 2017 Win64" ..

build:
  parallel: true
  verbosity: minimal
  project: build/slang.sln

test_script:
  - cmd: tests\unittests\Release\unittests.exe