language: cpp
sudo: false
dist: trusty

matrix:
  include:
    - env: BUILD_TARGET=linux-gcc
    #- env: BUILD_TARGET=linux-clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-7
      - g++-7
      - clang-5.0

install:
  - mkdir -p latest-symlinks
  - ln -s /usr/bin/clang++-5.0 latest-symlinks/clang++
  - ln -s /usr/bin/clang-5.0 latest-symlinks/clang
  - ln -s /usr/bin/g++-7 latest-symlinks/g++
  - ln -s /usr/bin/gcc-7 latest-symlinks/gcc
  - ln -s /usr/bin/gcov-7 latest-symlinks/gcov
  - export PATH=$PWD/latest-symlinks:$PATH
  - clang++ --version
  - g++ --version
  - tools/bin/linux/genie --gcc=$BUILD_TARGET --with-coverage gmake

script:
  - if [ "$BUILD_TARGET" == "linux-clang" ]; then make -C build/projects/gmake-linux-clang -j 8; build/linux64_clang/bin/unittestsDebug; fi
  - if [ "$BUILD_TARGET" == "linux-gcc" ]; then make -C build/projects/gmake-linux -j 8; build/linux64_gcc/bin/unittestsDebug; fi

branches:
  only:
    - /.*/

git:
  depth: 3

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'