language: cpp
sudo: required

services:
  - docker

matrix:
  include:
    - env: BUILD_TARGET=linux-gcc BUILD_FLAGS="--with-coverage"
    - env: BUILD_TARGET=linux-clang BUILD_FLAGS="--sanitizer=undefined,address"

before_install:
  - docker pull mpopoloski/slang:1.0
  - docker run -itd --name build mpopoloski/slang:1.0
  - docker exec build git clone https://github.com/MikePopoloski/slang.git

install:
  - docker exec build /bin/sh -c "cd slang && tools/bin/linux/genie --gcc=$BUILD_TARGET $BUILD_FLAGS gmake"

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - if [ "$BUILD_TARGET" == "linux-clang" ]; then docker exec build slang/scripts/build_clang.sh; fi
  - if [ "$BUILD_TARGET" == "linux-gcc" ]; then docker exec build $ci_env slang/scripts/build_gcc.sh; fi

branches:
  only:
    - /.*/

git:
  depth: 1