language: cpp
sudo: false

matrix:
  include:
    - env: BUILD_TARGET=linux-gcc
    - env: BUILD_TARGET=linux-clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-6
      - g++-6
      - clang-5.0

install:
  - mkdir -p latest-symlinks
  - ln -s /usr/bin/clang++-5.0 latest-symlinks/clang++
  - ln -s /usr/bin/clang-5.0 latest-symlinks/clang
  - ln -s /usr/bin/g++-6 latest-symlinks/g++
  - ln -s /usr/bin/gcc-6 latest-symlinks/gcc
  - export PATH=$PWD/latest-symlinks:$PATH
  - tools/bin/linux/genie --gcc=$BUILD_TARGET gmake

script:
  - if [ "$BUILD_TARGET" == "linux-clang" ]; then make -C build/projects/gmake-linux-clang -j 8; build/linux64_clang/bin/unittestsDebug; fi
  - if [ "$BUILD_TARGET" == "linux-gcc" ]; then make -C build/projects/gmake-linux -j 8; build/linux64_gcc/bin/unittestsDebug; fi

branches:
  only:
    - master

git:
  depth: 3