language: cpp

matrix:
  include:
    - env: BUILD_TARGET=linux-gcc-6
    - env: BUILD_TARGET=linux-clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - gcc-6
      - g++-6
      - clang-3.9

install:
  - mkdir -p latest-symlinks
  - ln -s /usr/bin/clang++-3.9 latest-symlinks/clang++
  - ln -s /usr/bin/clang-3.9 latest-symlinks/clang
  - export PATH=$PWD/latest-symlinks:$PATH
  - tools/bin/linux/genie --gcc=$BUILD_TARGET gmake

script:
  - if [ "$BUILD_TARGET" == "linux-clang" ]; then make -C build/projects/gmake-linux-clang -j 8; build/linux64_clang/bin/unittestsDebug; fi
  - if [ "$BUILD_TARGET" == "linux-gcc-6" ]; then make -C build/projects/gmake-linux -j 8; build/linux64_gcc/bin/unittestsDebug; fi

branches:
  only:
    - master

git:
  depth: 3