language: cpp
compiler:
  - clang++-3.9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9
    packages:
      - gcc-6
      - g++-6
      - clang-3.9

script:
  - cd build/linux && make -j 8 CXX=clang++-3.9
  - cd ../..
  - bin/linux/unittests

branches:
  only:
    - master

git:
  depth: 3