# Build script for continuous integration builds with Azure Pipelines

strategy:
  matrix:
    gcc:
      imageName: 'ubuntu-16.04'
      compiler: g++-8
      flags: ''
    clang:
      imageName: 'ubuntu-16.04'
      compiler: clang++-7
      flags: '-DSLANG_COVERAGE=ON -DSLANG_SANITIZERS=undefined,address "-DCMAKE_CXX_CLANG_TIDY=/usr/lib/llvm-7/bin/clang-tidy;-quiet;-checks=-*,clang-analyzer-*,bugprone-*,performance-*,modernize-*,-modernize-use-auto,-modernize-raw-string-literal,-bugprone-suspicious-semicolon,-clang-analyzer-cplusplus.NewDelete*,-clang-analyzer-cplusplus.InnerPointer,misc-*"'

pool:
  vmImage: $(imageName)

steps:
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update
    sudo apt-get install -y gcc-8 g++-8
  displayName: 'Install gcc 8'
  condition: eq(variables['compiler'], 'g++-8')

- script: |
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main" -y
    sudo apt-get update
    sudo apt-get install -y clang-7 clang-tidy-7
  displayName: 'Install clang 7'
  condition: eq(variables['compiler'], 'clang++-7')

- script: |
    sudo apt-get install -y python3-setuptools python3-pip
    pip3 install wheel conan
    conan user
  displayName: 'Install Conan'

- script: |
    mkdir build
    cd build
    cmake -DCMAKE_CXX_COMPILER=$(compiler) -DCMAKE_BUILD_TYPE=Debug -DCI_BUILD=ON $(flags) ..
    make -j 8
  displayName: 'Build'

- script: |
    ctest
  displayName: 'Run tests'