# Build script for continuous integration builds with Azure Pipelines

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo apt-get update
    sudo apt-get install -y gcc-8 g++-8
  displayName: 'Install GCC 8'

- script: |
    sudo apt-get install -y python3-setuptools python3-pip
    pip3 install --upgrade pip
    pip3 install conan
    conan user
  displayName: 'Install Conan'

- script: |
    mkdir build
    cd build
    cmake -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Debug -DCI_BUILD=ON ..
    make -j 8
  displayName: 'Build'

- script: |
    ctest
  displayName: 'Run tests'