name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: cmake --preset win64-release -DSLANG_INCLUDE_PYLIB=ON
    - name: Build
      run: cmake --build build/win64-release --target install -j8
    - name: Run tests
      run: |
        cd build/win64-release
        ctest --output-on-failure

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Configure
        run: cmake --preset macos-release
      - name: Build
        run: cmake --build build/macos-release --target install -j8
      - name: Run tests
        run: |
          cd build/macos-release
          ctest --output-on-failure

  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - preset: clang-ci-coverage
          - preset: gcc-release
          - preset: gcc-9-release

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Install dependencies
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main"
        sudo apt-get update
        sudo apt-get install -y g++-12 g++-9 clang++-14 clang-tidy-14
    - name: Configure
      run: cmake --preset ${{ matrix.preset }} -DCI_BUILD=ON
    - name: Build
      run: cmake --build build/${{ matrix.preset }} --target install -j8
    - name: Run tests
      run: |
        export LLVM_PROFILE_FILE=%p.profraw
        cd build/${{ matrix.preset }}
        ctest --output-on-failure
    - name: Upload code coverage
      if: matrix.preset == 'clang-ci-coverage'
      run: |
        cd build/${{ matrix.preset }}
        find . -name *.profraw -exec llvm-profdata-14 merge -o merged.profdata -sparse {} + ;
        llvm-cov-14 show bin/unittests -instr-profile=merged.profdata > coverage.txt
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
