name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_msvc:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - name: Configure
      shell: bash
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -DCMAKE_INSTALL_PREFIX=$HOME/slang/
    - name: Build
      run: msbuild build/INSTALL.vcxproj -m -p:configuration=release -p:platform=x64
    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure
    - name: Archive binaries
      run: |
        Compress-Archive $HOME/slang/ slang-windows.zip
    - name: Upload artifacts
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: SLANG_ARTIFACT_WIN
        path: slang-windows.zip

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/slang/
      - name: Build
        run: |
          cd build
          make install -j8
      - name: Run tests
        run: ctest --output-on-failure
      - name: Archive binaries
        run: tar -czvf slang-macos.tar.gz -C $HOME slang/
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: SLANG_ARTIFACT_MACOS
          path: slang-macos.tar.gz

  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - compiler: clang++-14
            flags: '-DCMAKE_BUILD_TYPE=Debug -DSLANG_COVERAGE=ON -DSLANG_SANITIZERS=undefined,address "-DCMAKE_CXX_CLANG_TIDY=/usr/lib/llvm-14/bin/clang-tidy;-quiet;-checks=-*,clang-analyzer-*,bugprone-*,performance-*,modernize-*,-modernize-use-auto,-modernize-use-trailing-return-type,-modernize-raw-string-literal,-modernize-use-nodiscard,-bugprone-suspicious-semicolon,-bugprone-branch-clone,-bugprone-sizeof-expression,-clang-analyzer-cplusplus.NewDelete*,-clang-analyzer-cplusplus.InnerPointer,misc-*,-misc-non-private-member-variables-in-classes,-modernize-avoid-c-arrays,-misc-no-recursion,-modernize-use-emplace,-performance-no-int-to-ptr,-bugprone-easily-swappable-parameters,-modernize-return-braced-init-list,-bugprone-implicit-widening-of-multiplication-result"'
          - compiler: g++-12
            flags: '-DCMAKE_BUILD_TYPE=Release'
          - compiler: g++-8
            flags: '-DCMAKE_BUILD_TYPE=Debug'

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main"
        sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu focal main universe"
        sudo apt-get update
        sudo apt-get install -y g++-12 g++-8 clang++-14 clang-tidy-14
    - name: Build
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DCI_BUILD=ON ${{ matrix.flags }} -DCMAKE_INSTALL_PREFIX=$HOME/slang/
        make install -j8
    - name: Run tests
      run: |
        export LLVM_PROFILE_FILE=%p.profraw
        cd build
        ctest --output-on-failure
    - name: Upload code coverage
      if: matrix.compiler == 'clang++-14'
      run: |
        cd build
        find . -name *.profraw -exec llvm-profdata-14 merge -o merged.profdata -sparse {} + ;
        llvm-cov-14 show bin/unittests -instr-profile=merged.profdata > coverage.txt
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
    - name: Archive binaries
      if: matrix.compiler == 'g++-12'
      run: |
        strip --strip-unneeded $HOME/slang/bin/*
        strip --strip-unneeded $HOME/slang/lib/*
        tar -czvf slang-linux.tar.gz -C $HOME slang/
    - name: Upload artifacts
      if: matrix.compiler == 'g++-12' && github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: SLANG_ARTIFACT_LINUX
        path: slang-linux.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: [build_msvc, build_macos, build_linux]
    if: github.event_name == 'push'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: SLANG_ARTIFACT_WIN
    - uses: actions/download-artifact@v2
      with:
        name: SLANG_ARTIFACT_LINUX
    - uses: actions/download-artifact@v2
      with:
        name: SLANG_ARTIFACT_MACOS
    - uses: meeDamian/github-release@2.0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        name: Nightly
        tag: nightly
        body: This is an autogenerated release from the last successful continuous integration build. The included prebuilt binaries should be considered unstable.
        prerelease: true
        allow_override: true
        gzip: false
        files: slang-linux.tar.gz slang-windows.zip slang-macos.tar.gz
