name: docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - uses: actions/checkout@v2
      with:
        name: MikePopoloski/m.css
    - name: Install dependencies
      run: |
        pip install jinja2 pygments
        wget http://doxygen.nl/files/doxygen-1.8.17.linux.bin.tar.gz
        tar -xvf doxygen-1.8.17.linux.bin.tar.gz
        cp doxygen-1.8.17/bin/doxygen /usr/local/bin
    - name: Build
      run: |
        cmake -B build -DSLANG_INCLUDE_DOCS=ON -DSLANG_INCLUDE_TESTS=OFF -DDOXYGENPY_PATH=m.css/documentation/doxygen.py
        cmake --build build --target docs
