name: Lint

on:
  push:
  pull_request:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install black==25.1.0 flake8==7.3.0 flake8-bugbear isort==6.0.1 cmake-format==0.6.13 pyyaml
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Run Black
      run: |
        black --check --diff . --exclude="docs/"

    - name: Run flake8
      run: |
        flake8 .

    - name: Run isort
      run: |
        isort --check-only --diff .

    - name: Run clang-format
      run: |
        find . -name "*.cpp" -o -name "*.h" | grep -v "^./external/" | xargs clang-format --dry-run --Werror

    - name: Run cmake-format
      run: |
        find . \( -name "*.cmake" -o -name "CMakeLists.txt" \) -exec cmake-format --check {} \;
